# Generated by Django 5.1.4 on 2025-01-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='runningtime',
            field=models.IntegerField(),
        ),
    ]
