# Generated by Django 5.1.5 on 2025-01-19 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pirostagrams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
