# Generated by Django 5.1.4 on 2025-01-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='IdeaStar',
            field=models.BooleanField(default=False, verbose_name='찜하기'),
        ),
    ]
